# grizzly fingerprint: 5amxy70cyz48sj89t7exyzmqywhvwqh2
identity_seed: miracle-tank-settle-fiction-spice-north-birth-season-rebuild-distance-recall-wing
in_routes:
  main_udp:
    listen: 0.0.0.0:12090
    protocol: obfsudp
    secret: reunion-height-mesh-bargain-abstract-couple-tower-bacon-east-address-grocery-again
out_routes:
  chimp:
    connect: 200.64.1.85:12168
    cookie: adde574f7bbe43fa6e70155f05cb9f86f6a9dcb909873d0dc8415a10eb99e717
    fingerprint: fqjtasvgw228e8phchy8eb3s57vad6q5
    protocol: obfsudp
  joey:
    connect: 200.64.1.23:12044
    cookie: 034efc21671fc352b6f801ad925f840e49fd30345a976fea8f63aaa59cac7b5a
    fingerprint: 06f05dzj20wy1whq3wc1qmnzct4c2amc
    protocol: obfsudp
  yeti:
    connect: 200.64.1.19:12036
    cookie: c83eaa3f7d25b34a9e20b32df4da82928f7678a704149a9b991dab345005c90d
    fingerprint: bw1v3rztvrh49cyxaqzn42719rjj2mj2
    protocol: obfsudp
