[workspace]
members = ["libraries/*"]

[package]
name = "earendil"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.163", features=["derive"]}
serde_with = {version="3.0.0", features=["hex"]}
earendil_packet={path="libraries/earendil_packet"}
earendil_topology={path="libraries/earendil_topology"}
serde_yaml = "0.9.21"
clap = {version="4.3.1", features=["derive"]}
anyhow = "1.0.71"
hex = "0.4.3"
stdcode = "0.1.14"
log = "0.4.18"
env_logger = "0.10.0"
nanorpc = "0.1.12"
async-trait = "0.1.68"
bytes = "1.4.0"
blake3 = "1.3.3"
sosistab2 = "0.8.17"
concurrent-queue = "2.2.0"
smol = "1.3.0"
scopeguard = "1.1.0"
serde_json = "1.0.96"
bytemuck = "1.13.1"
smolscale = "0.3.52"
thiserror = "1.0.40"
futures-util = "0.3.28"
dashmap = "5.4.0"




[profile.release-dbg]
inherits = "release"
debug = 2
