[package]
name = "earendil_packet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
blake3 = "1.3.3"
bytemuck = {version="1.13.1", features=["derive", "min_const_generics"]}
bytes = "1.4.0"
chacha20 = "0.9.1"
chacha20poly1305 = "0.10.1"
ed25519-compact = "2.0.4"
rand = "0.8.5"
thiserror = "1.0.40"
serde = {version = "1.0.163", features=["derive"]}
base64 = "0.21.2"
