# flamingo fingerprint: dspq68f5fqgks0vcj9ghcx3mqvsypwvs
identity_seed: gentle-proud-income-erupt-notice-scrap-evolve-change-winner-head-coyote-goat
in_routes:
  main_udp:
    listen: 0.0.0.0:12008
    protocol: obfsudp
    secret: ten-fame-raccoon-lazy-obey-myth-dilemma-motion-owner-pig-output-melody
out_routes:
  bream:
    connect: 200.64.1.61:12120
    cookie: 144325d77af008e74e9333a8e86800d8abdb497ed38717adff26de163730d94c
    fingerprint: ajq74w1svhz94dfpz3p928prnveyamp1
    protocol: obfsudp
  lioness:
    connect: 200.64.1.18:12034
    cookie: 23d38d1c9d3ec20366e8f74022b127bc5c0e99a09cbf41c6e20ae47d63326123
    fingerprint: ser0em4w49qfcwemtd3yv08r6p9nz99t
    protocol: obfsudp
  pipefish:
    connect: 200.64.1.73:12144
    cookie: 9fbc59d3752f8f6390bfd14a96ce06af7be1f85b16c12813f4e8d6e6036d3b4a
    fingerprint: 8fvmf7sk3w7mkcqyznzc0ax86qx194h1
    protocol: obfsudp
