# rob fingerprint: exs0023e1x76fdwc54cvax8ty3x32t3f
control_listen: 127.0.0.1:12001
identity_seed: protect-december-lawn-regular-yellow-choice-attack-quiz-sort-sketch-castle-connect
in_routes:
  main_udp:
    listen: 0.0.0.0:12000
    protocol: obfsudp
    secret: company-elbow-switch-theory-grant-sleep-entry-session-spike-name-battle-climb
out_routes:
  bob:
    connect: 127.0.0.1:12004
    cookie: 68180a33c503452d077c13af4a9aabf4280c83de120d0a7c2776a6e3e2510e5d
    fingerprint: ztt6sy7xgxjkf1t93zqsjqz5mq9rdd52
    protocol: obfsudp
