# foxhound fingerprint: z67616mzjwsx9bvqhkm3ayagfm0rhawk
identity_seed: salute-toward-claw-chronic-balcony-payment-spirit-fall-actress-mercy-tomorrow-insect
in_routes:
  main_udp:
    listen: 0.0.0.0:12094
    protocol: obfsudp
    secret: design-axis-crawl-deposit-session-travel-gather-attitude-winner-pudding-topple-idea
out_routes:
  bream:
    connect: 200.64.1.61:12120
    cookie: 144325d77af008e74e9333a8e86800d8abdb497ed38717adff26de163730d94c
    fingerprint: ajq74w1svhz94dfpz3p928prnveyamp1
    protocol: obfsudp
  impala:
    connect: 200.64.1.54:12106
    cookie: d5cc9657f08a0703348b7627d1ec242940ba9437c55f9a31e820026450d19422
    fingerprint: dne6878hkx6qp2ftq81aky5ecvw3aby1
    protocol: obfsudp
  wildcat:
    connect: 200.64.1.68:12134
    cookie: 3101cb06cdf6b9390d16716091e0d401c295855c064dd486916c799b6478157e
    fingerprint: vmp4qb0bgs8rbbdzh0dh05b9e6jgpg6s
    protocol: obfsudp
