# fingerprint: rxccpfn94v0j223qabk1s8aahfa2d1tc
identity: ./src/config/alice.asc
state_cache: state_cache_alice.db
control_listen: 127.0.0.1:11111

in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:19999
    secret: correct horse battery staple
