# parrot fingerprint: 2s03aj3jq05jfv6nnzpby4g1vxg6snkq
identity_seed: pole-endorse-either-response-arena-dirt-eagle-below-remember-script-carpet-hope
in_routes:
  main_udp:
    listen: 0.0.0.0:12030
    protocol: obfsudp
    secret: crunch-syrup-skull-month-then-guitar-course-robot-attend-approve-clever-coconut
out_routes:
  bee:
    connect: 200.64.1.30:12058
    cookie: e6f5c8f1aa31892383820c7889b3340912d4607e217cf573e2f3a8ddcd3f9c75
    fingerprint: zqxwhwahpjp5dj8jrcfx9e1bn04h9tsz
    protocol: obfsudp
  impala:
    connect: 200.64.1.54:12106
    cookie: d5cc9657f08a0703348b7627d1ec242940ba9437c55f9a31e820026450d19422
    fingerprint: dne6878hkx6qp2ftq81aky5ecvw3aby1
    protocol: obfsudp
  yeti:
    connect: 200.64.1.19:12036
    cookie: c83eaa3f7d25b34a9e20b32df4da82928f7678a704149a9b991dab345005c90d
    fingerprint: bw1v3rztvrh49cyxaqzn42719rjj2mj2
    protocol: obfsudp
