# fingerprint: w0pj999ezrc36spw5zz88nn79z9h7mss
identity: identity.asc
state_cache: state_cache.db

in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:19999
    secret: correct horse battery staple

# client config
udp_forward_config:
  forward_to: 9910
  remote_ep: fhsg3742bwxmg3k14jdsbphdp22j119f::69420
