identity: /tmp/identity.asc
state_cache: /tmp/state_cache.db
in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:19999
    secret: correct horse battery staple
out_routes:
  loopback:
    fingerprint: iR0zm9OYDspNGNJ19LNSfpu1I6Y
    protocol: obfsudp
    connect: 127.0.0.1:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
