identity: /tmp/identity2.asc
state_cache: /tmp/state_cache2.db
control_listen: 127.0.0.1:11111

out_routes:
  loopback:
    fingerprint: iR0zm9OYDspNGNJ19LNSfpu1I6Y
    protocol: obfsudp
    connect: 127.0.0.1:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
