identity: identity2.asc
state_cache: state_cache2.db

out_routes:
  neighbor:
    fingerprint: w0pj999ezrc36spw5zz88nn79z9h7mss
    protocol: obfsudp
    connect: 127.0.0.1:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
