# fingerprint: w0pj999ezrc36spw5zz88nn79z9h7mss

identity: identity.asc
state_cache: state_cache.db

in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:19999
    secret: correct horse battery staple

out_routes:
  server:
    fingerprint: 83kv9hb6jfxdnp9fwj7x5s417v2d2wx9
    protocol: obfsudp
    connect: 164.92.86.192:42000
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d

# client config
udp_forwards:
  - forward_to: 8080
    remote_ep: fhsg3742bwxmg3k14jdsbphdp22j119f:69420

