# gopher fingerprint: 7sgzgjq1fnffkh6c5ync7nd75ef7z321
identity_seed: game-season-twenty-weapon-ladder-gather-federal-jar-juice-thing-crew-water
in_routes:
  main_udp:
    listen: 0.0.0.0:12078
    protocol: obfsudp
    secret: service-today-pulse-evoke-cricket-pencil-unfair-indoor-input-fence-spell-mercy
out_routes:
  chimp:
    connect: 200.64.1.85:12168
    cookie: adde574f7bbe43fa6e70155f05cb9f86f6a9dcb909873d0dc8415a10eb99e717
    fingerprint: fqjtasvgw228e8phchy8eb3s57vad6q5
    protocol: obfsudp
  katydid:
    connect: 200.64.1.10:12018
    cookie: 62c10ebbc1ffb0624eb3c8eb70dcaa7b142f60d45080e29b5659ba97695d7e0e
    fingerprint: gksmy18w78z5xqq9kf4tsvagckzzkk07
    protocol: obfsudp
  serval:
    connect: 200.64.1.29:12056
    cookie: d9a1266d6d89e1397d5e03572b646ee850b506dfa9169bd06d06c734beee8357
    fingerprint: kb4g0tk7c8ggfn7rth1cfsjdcgvnaseg
    protocol: obfsudp
