# impala fingerprint: dne6878hkx6qp2ftq81aky5ecvw3aby1
identity_seed: become-asset-anger-flag-panel-tourist-horn-volume-hip-exhibit-ridge-enough
in_routes:
  main_udp:
    listen: 0.0.0.0:12106
    protocol: obfsudp
    secret: occur-garden-hold-consider-include-dizzy-marble-velvet-uncover-letter-sunset-tomato
out_routes:
  rhino:
    connect: 200.64.1.38:12074
    cookie: 5ae4a7bd964615d3201dc33fc60aeeb818985055cfc67a53b6748dc7def60968
    fingerprint: 54wp8pnksmqyzyc1t605879y7gb6x1f7
    protocol: obfsudp
  silkworm:
    connect: 200.64.1.78:12154
    cookie: faa454626a10b2a84662313758b29b7fad7e25de855c4cc824940376b355ac3f
    fingerprint: kzppgt7k68emxtgm31xfkjqpram5b37s
    protocol: obfsudp
  tuna:
    connect: 200.64.1.82:12162
    cookie: 701472e7da1e8d1827e640051fb21937b1405cb8b3fe1a92014f5fd8b96e7a24
    fingerprint: 4rafcceggd2kc93x9c4aq8dsxx88baxq
    protocol: obfsudp
