# midge fingerprint: atf9kaj0m8xtwd6byeskw56dzpsza66r
identity_seed: lesson-nation-tattoo-tree-toe-senior-sister-build-train-finger-gauge-awful
in_routes:
  main_udp:
    listen: 0.0.0.0:12070
    protocol: obfsudp
    secret: equal-slab-hundred-current-bunker-abandon-myself-small-program-attract-catalog-usage
out_routes:
  bat:
    connect: 200.64.1.41:12080
    cookie: a067284db4e2369355478edf21d5d18eef66dff29b237792fba30f983c312d70
    fingerprint: dtprzzgm0e0z07pj68d3q89br906ejnz
    protocol: obfsudp
  oriole:
    connect: 200.64.1.14:12026
    cookie: 4b3c1cfdf87219ac3028d5c0913f9a8a66d0b19b9bd95c2b9e2132603ce4503f
    fingerprint: czmtb9zr99sj7e04d7twc1zs4vtqmxda
    protocol: obfsudp
  seal:
    connect: 200.64.1.26:12050
    cookie: 0d3785400d2c5ca49e8e23b70910541c17d6ef8c1712668a5b539e9727371936
    fingerprint: h2gpxqb11vn9575cdaednh2a6b691bg2
    protocol: obfsudp
