# grackle fingerprint: 0pqfmgs7fgp5z5gws602df0gdt4y3rab
identity_seed: detail-virtual-phone-retreat-hybrid-view-clown-above-mass-index-behind-tray
in_routes:
  main_udp:
    listen: 0.0.0.0:12172
    protocol: obfsudp
    secret: iron-wrong-gift-indicate-blast-coast-panther-crack-chronic-dwarf-abuse-blast
out_routes:
  shrew:
    connect: 200.64.1.9:12016
    cookie: aa9b73155438b0c6ef7d4e8eb331477dd147c3de3e4c5851a78b886cbbb52c41
    fingerprint: rtnw7f3fc3kx4tw1qv57wzbb33fzs1y9
    protocol: obfsudp
  toad:
    connect: 200.64.1.66:12130
    cookie: 88a1df8122790b2a652e91312c4d6abaa7e0e4c5eed914440b6066cc0e621a4e
    fingerprint: 3jw0rgz7hh7jp27njtvdrb4a1h1br07n
    protocol: obfsudp
  wolf:
    connect: 200.64.1.43:12084
    cookie: f8886d213b86d3878ad5fb3fabd403b3f8f6e884bff84ef8470f4af148886131
    fingerprint: rphdzr3bmt5j3spjy2rbtewtndk6rmst
    protocol: obfsudp
