name: Build Artifacts

on:
  push:
    branches:
      - build
  # pull_request:
  #   branches:
  #     - build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Install Rust and Cross
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            cargo install cross
          else
            sudo apt-get update
            sudo apt-get install -y musl-tools
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            cargo install cross
          fi

      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate artifacts
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            cargo build --release --target x86_64-apple-darwin
            mkdir -p earendil.app/Contents/MacOS
            cp target/x86_64-apple-darwin/release/earendil earendil.app/Contents/MacOS/earendil
            zip -r earendil-macos.zip earendil.app
          else
            cd utilities/earendil-gui
            cross build --target x86_64-pc-windows-gnu --release
          fi
        env:
          PKG_CONFIG_ALLOW_CROSS: 1

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            target/x86_64-pc-windows-gnu/release/
            target/x86_64-apple-darwin/release/
