name: Build Artifacts

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust and Cross
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools glibc-source
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install cross

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build artifacts for Windows
        run: cross build --target x86_64-pc-windows-gnu --release
        env:
          PKG_CONFIG_ALLOW_CROSS: 1


      - name: Build artifacts for Linux
        run: |
          rustup target add x86_64-unknown-linux-musl
          cross build --target x86_64-unknown-linux-musl --release
        env:
          PKG_CONFIG_ALLOW_CROSS: 1

      # - name: Build artifacts for Mac
      #   run: |
      #     rustup target add x86_64-apple-darwin
      #     cross build --target x86_64-apple-darwin --release
      #   env:
      #     PKG_CONFIG_ALLOW_CROSS: 1


      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            target/x86_64-pc-windows-gnu/release/
            target/x86_64-apple-darwin/release/
            target/x86_64-unknown-linux-musl/release/
